Repository andoriyaprashant/Swoofy, pull requests merged in 2023-10, with the labels that each got.

#9 Create a Contributing.md file for new contributors
  CONTRIBUTING
  README.md
Labels: documentation, good first issue, flutter, hacktoberfest, hacktoberfest-accepted

#10 -:hammer: andoriyaprashant/Swoofy#4 fixed unnecessary app crash
  android/app/src/main/AndroidManifest.xml
  lib/controllers/player_controllar.dart
  lib/views/home.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#12 ci: Add CI
  .github/workflows/auto-comment.yml
  .github/workflows/ci.yml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
